_target_: evals.models.dino_reg.DINO_REG
dino_name: dinov2
model_name: vitb14_reg
output: dense-cls
layer: -1
teacher_checkpoint: /work/dlclarge2/sunagadb-runs/dinov2/outputs_b14/eval/training_124999/teacher_checkpoint.pth
